'use strict'

###*
# @ngdoc function
# @name four4App.directive:waveformDirective
# @description
# # waveformDirective
###

angular.module('four4App').directive 'fourWaveform', ->
  {
    replace: true
    templateUrl: 'components/decks/waveform.html'
    scope:
      deck: '='
    link: ($scope, element, attr) ->
        deck = $scope.deck
        deck.canvas = canvas = $('canvas', element).get(0)
        context = canvas.getContext('2d')
        deck.animate_waveform = () =>
            deck.animating = setTimeout(() ->
              requestAnimationFrame(deck.animate_waveform)
            , 10)
            if not deck.song.ready or not deck.song.analyzed
                return
            AC = deck.song.context
            SR = AC.sampleRate
            CW = deck.canvas.width
            H=deck.canvas.height
            half = CW/2 | 0
            pct = (deck.song.audio_tag.currentTime / deck.song.audio_tag.duration)
            S = pct * (deck.song.analyze_width) | 0
            context.clearRect 0, 0, CW, H
            a = -half
            while a < half
              context.fillStyle = 'hsla(200,100%,70%,0.7)'
              context.fillRect a + half, H/2, 1, deck.song.analyzed[a + S] or 0
              context.fillRect a + half, H/2, 1, -deck.song.analyzed[a + S] or 0
              a++
            context.fillStyle = 'hsla(0,0%,100%,1)'
            context.fillRect half, 0, 1, H
        requestAnimationFrame(deck.animate_waveform)
        root.deck = $scope.deck
        return
  }

# ---
# generated by js2coffee 2.0.1
