'use strict'

###*
# @ngdoc function
# @name four4App.directive:waveformDirective
# @description
# # waveformDirective
###

angular.module('four4App').directive 'fourWaveform', ->
  {
    replace: true
    templateUrl: 'components/decks/waveform.html'
    scope:
      deck: '='
    link: ($scope, element, attr) ->
        canvas = $('canvas', element).get(0)
        context = canvas.getContext('2d')
        console.log('canvas')
        root.scope = $scope
        root.stage = $scope.deck.stage
        root.song = $scope.deck.song
        root.deck = $scope.deck
        root.canvas = $scope.canvas
        return
  }

# ---
# generated by js2coffee 2.0.1
